name: balenciaga_ecommerce
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  flutter_svg: ^2.2.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.1
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3
  http: ^1.2.2
  gradient_borders: ^1.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/balenciagalogo.jpg
    - assets/icons/
    - assets/images/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/plus-jakarta-sans/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/plus-jakarta-sans/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/plus-jakarta-sans/PlusJakartaSans-Light.ttf




flutter_native_splash:
  color: "#000000"         
  image: assets/balenciagalogo.jpg
  android: true
  ios: true
