// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2l8CNm7WMI95_1iV1SVinRPq6UFioYLw',
    appId: '1:949220345319:web:1e24e164d297cbf06ca942',
    messagingSenderId: '949220345319',
    projectId: 'balenciagaauth',
    authDomain: 'balenciagaauth.firebaseapp.com',
    storageBucket: 'balenciagaauth.firebasestorage.app',
    measurementId: 'G-470PGPZQE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA93frok4hdAT-dSDjMlVSwoG692JJuVJQ',
    appId: '1:949220345319:android:fb6ef71409fd392e6ca942',
    messagingSenderId: '949220345319',
    projectId: 'balenciagaauth',
    storageBucket: 'balenciagaauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6-mvcOnFPH8KYmihu2jsLTS04e0PQNf8',
    appId: '1:949220345319:ios:53b0be8c64668caa6ca942',
    messagingSenderId: '949220345319',
    projectId: 'balenciagaauth',
    storageBucket: 'balenciagaauth.firebasestorage.app',
    iosBundleId: 'com.example.balenciagaEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6-mvcOnFPH8KYmihu2jsLTS04e0PQNf8',
    appId: '1:949220345319:ios:53b0be8c64668caa6ca942',
    messagingSenderId: '949220345319',
    projectId: 'balenciagaauth',
    storageBucket: 'balenciagaauth.firebasestorage.app',
    iosBundleId: 'com.example.balenciagaEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2l8CNm7WMI95_1iV1SVinRPq6UFioYLw',
    appId: '1:949220345319:web:8855ca4e56f8efb66ca942',
    messagingSenderId: '949220345319',
    projectId: 'balenciagaauth',
    authDomain: 'balenciagaauth.firebaseapp.com',
    storageBucket: 'balenciagaauth.firebasestorage.app',
    measurementId: 'G-YF47K51D7P',
  );

}